global using System;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using UnityEngine;
global using static UnityEngine.Object;
global using JFUtils;
global using static JFUtils.ModBase;
global using static UnityEngine.Mathf;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Globalization;
global using BepInEx.Configuration;
global using System.IO;